pothole_detector_single:
  ros__parameters:
    use_sim_time: true
    base_frame: base_link
    output_frame: odom
    ground_z_in_base: 0.0

    image_topic: /left_cam/image_raw
    info_topic: /left_cam/camera_info
    cam_frame: left_camera_link/left_cam

    roi_top_frac: 0.35
    sat_max_for_white: 60
    val_min_for_white: 220
    open_k: 9
    close_k: 7

    min_area_px: 200.0
    max_area_px: 50000.0
    min_circularity: 0.65
    max_aspect_ratio: 1.6

    pothole_radius_m: 0.3048
    cluster_dist_m: 0.35

    track_match_dist: 0.75
    track_alpha: 0.08
    track_ttl_sec: 2.0
    min_hits_to_publish: 2
    max_jump_m: 0.60